name: Laravel Docker Deploy


on:

  push:

    branches:

      - main



jobs:


  build:


    runs-on: ubuntu-latest


    steps:


      - name: Checkout

        uses: actions/checkout@v4



      - name: Build Docker

        run: |

          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_ACCESS_TOKEN}}
          docker build \
          -t bennedistus/forge-flows:v1 .
          docker push bennedistus/forge-flows:v1
          



  deploy:


    needs: build

    runs-on: ubuntu-latest



    steps:


      - name: SSH Deploy VPS

        uses: appleboy/ssh-action@v1.0.3


        with:


          host: ${{ secrets.VPS_HOST }}

          username: ${{ secrets.VPS_USER }}

          key: ${{ secrets.VPS_SECRET }}



          script: |


            cd /home/project/ForgeFlows
            
            
            git pull origin main
            
            docker compose down -v
            docker compose pull
            docker compose up -d

            sleep 8

            docker compose exec app php artisan migrate --force
            docker compose exec app php artisan key:generate

            docker compose exec app php artisan optimize